import {
    Activity,
    BarChart3,
    BookOpen,
    Briefcase,
    Database,
    FileClock,
    FileText,
    FolderOpen,
    Home,
    LayoutDashboard,
    LifeBuoy,
    LogIn,
    LogOut,
    MapPin,
    MessageSquare,
    Receipt,
    Settings,
    Shield,
    ShoppingCart,
    Users,
} from 'lucide-react';

const ICON_BY_KEY = {
    'nav.home': Home,
    'nav.dashboard': LayoutDashboard,
    'nav.projects': FolderOpen,
    'nav.closurePanel': FileText,
    'nav.adminPanel': Shield,
    'nav.adminDashboard': Shield,
    'nav.directionPanel': FileText,
    'nav.clients': Users,
    'nav.stations': MapPin,
    'nav.works': Briefcase,
    'nav.createWork': Briefcase,
    'nav.orders': ShoppingCart,
    'nav.invoices': Receipt,
    'nav.imports': Activity,
    'nav.masterData': Database,
    'nav.audit': FileClock,
    'nav.activityLog': FileClock,
    'nav.adminUsers': Users,
    'nav.legalizations': FileText,
    'nav.reports': BarChart3,
    'nav.configuration': Settings,
    'nav.myProfile': Settings,
    'nav.help': BookOpen,
    'nav.messages': MessageSquare,
    'nav.support': LifeBuoy,
    'nav.status': Activity,
    'nav.systemStatus': Activity,
    'common.actions.logOut': LogOut,
    'nav.login': LogIn,
};

export function getNavigationIcon(key) {
    return ICON_BY_KEY[key] ?? null;
}
